### ISSUE TITLE
Create document makes unnecessary GET request

### ISSUE THREAD

**Issue by glynnbird** [ibm-watson-data-lab/php-couchdb#6]
IF I create a new document with:

    $test_db->create(["name" => "Alice", "interests" => ["eating", "wondering"]]);

the library does a 

- POST /db/ API call to create the document
- GET /db/id API call to fetch it back

The second API call could be removed without affecting the functionality with something like

    $doc['_id'] = $response_data['id'];
    $doc['_rev'] = $response_data['rev'];
    return $doc;

i.e. return the document body with the _id and _rev appended to it (without having to fetch it from the server).

Doing a quick POST + GET can expose eventual consistency problems in a distributed system i.e. you create a document in one part of the cluster and fail to GET it back before it has propagated to the other side.

**Comment by glynnbird** [comment]
The document update function also makes a  GET request too. That could be removed too.

**Comment by lornajane** [comment]
I did both of those intentionally, wanting to make sure that we only had values that the server had.  I'm not sure where I want to be in terms of defensive vs performant.

**Comment by glynnbird** [comment]
If you get a CouchDB 201 back, that guarantees your data is paged to disk (or on Cloudant, is on disk on a quorum of servers), so you needn't do any additional work. As I say in the post, occasionally, if you're unlucky, you'll get eventual consistency problems too.

**Comment by glynnbird** [comment]
Also with hosted Cloudant you have a quota of API calls, so the fewer the better :)
